
---
# tasks file for odoo_role
- name: Check if target directory exists
  stat:
    path: "{{ target_dir }}"
  register: dir_check

- name: Set working directory
  set_fact:
    working_dir: "{{ target_dir if dir_check.stat.exists else fallback_dir }}"

- name: Display working directory
  debug:
    msg: "Le répertoire de travail est : {{ working_dir }}"

- name: Generate and start Docker Compose
  block:
    - name: "Generate docker compose file"
      template:
        src: "docker-compose-odoo.yml.j2"
        dest: "{{ working_dir }}/docker-compose-odoo.yml"
        mode: '0644'

    - name: "Start docker compose"
      command: "docker compose -f {{ working_dir }}/docker-compose-odoo.yml up -d"
  
  vars:
    ansible_become: yes  # Si vous avez besoin de privilèges élevés
  when: working_dir is defined

- name: Warn if fallback directory was used
  debug:
    msg: "Attention : Le répertoire de repli ({{ fallback_dir }}) a été utilisé car {{ target_dir }} n'existe pas."
  when: working_dir == fallback_dir