pipeline {
    environment{
        DOCKER_USERNAME = 'ulrichsteve'
        IMAGE_NAME='icgroup'
        IMAGE_TAG='1.0'
        DOCKERHUB_PASSWORD = credentials('dockerhub_password')
        SERVER_PORT='8081'
        CONTAINER_PORT='8080'
        SERVER_IP='3.89.228.85'
    }
    agent none
    stages {
        stage ('Build'){
            agent any
            steps {
                script {
                     sh '''
                        docker build --no-cache -f ../Docker/ -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ../Docker
                     '''   
                }
            }
        }
        stage ('Test'){
            agent any
            steps {
                script {
                    sh '''
                        docker ps -a | grep -i $IMAGE_NAME && docker rm -f $IMAGE_NAME
                        docker run --rm -dp $SERVER_PORT:$CONTAINER_PORT --name $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
                        sleep 5
                        curl -I http://$SERVER_IP:$SERVER_PORT | grep -i "200"
                        docker stop $IMAGE_NAME
                        sleep 5
                    '''
                    
                }
            }
        }
        stage ('Release'){
            agent any
            steps {
                script {
                    sh '''
                        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                        docker push   $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }
    }
}