---
- name: update ubuntu os
  apt:
    update_cache: yes 
    upgrade: dist 

- name: install packages
  apt:
    name: "{{ item }}"
    state: present 
  loop:
    - curl
    - python3
    - python3-pip
    - ca-certificates
    - apt-transport-https
    - software-properties-common
  tags: always

- name: get docker script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: start docker install
  command: sh /tmp/get-docker.sh
  become: true

- name: check docker group
  group:
    name: docker
    state: present

- name: start docker
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: add user to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true 
  notify: restart docker

- name: install docker compose 
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: install docker python package
  pip:
    name: docker-py
    state: present
    executable: pip3
    extra_args: --break-system-packages